package com.example.fitnesstracker;

import android.content.Context;

public class DBSetupInsert {

    private final Context context;

    // Constructor
    public DBSetupInsert(Context ctx){
        this.context = ctx;
    }

    // Insert to food
    public void setupInsertToFood(String values){
        DBAdapter db = new DBAdapter(context);
        db.open();

        db.insert("food",
                "food_id, food_name, food_serving_size, food_serving_measurement, food_serving_name_number, food_serving_name_word, food_calories, food_energy, food_proteins, food_carbohydrates, food_fat, food_energy_calculated, food_proteins_calculated, food_carbohydrates_calulated, food_fat_calculated, food_user_id, food_barcode, food_category_id, food_image_a, food_image_b, food_image_c, food_description",
                values);
        db.close();
    }

    // Insert all food
    public void insertAllFood(){
        setupInsertToFood("1, 'Chicken Breast', 100, 'g', 1, 'breast', 165, 690, 31, 0, 3.6, 165, 31, 0, 3.6, 1, 0, 1, 'chicken_breast_a', 'chicken_breast_b', 'chicken_breast_c', 'Chicken breast is a great source of lean protein. It is also a great source of vitamin B6, phosphorus, niacin, and selenium. Chicken breast is also a good source of choline, pantothenic acid, and vitamin B12.'");
        setupInsertToFood("2, 'Chicken Thigh', 100, 'g', 1, 'thigh', 209, 873, 28, 0, 9.3, 209, 28, 0, 9.3, 1, 0, 1, 'chicken_thigh_a', 'chicken_thigh_b', 'chicken_thigh_c', 'Chicken thigh is a great source of lean protein. It is also a great source of vitamin B6, phosphorus, niacin, and selenium. Chicken thigh is also a good source of choline, pantothenic acid, and vitamin B12.'");
        setupInsertToFood("3, 'Chicken Drumstick', 100, 'g', 1, 'drumstick', 172, 718, 28, 0, 7.6, 172, 28, 0, 7.6, 1, 0, 1, 'chicken_drumstick_a', 'chicken_drumstick_b', 'chicken_drumstick_c', 'Chicken drumstick is a great source of lean protein. It is also a great source of vitamin B6, phosphorus, niacin, and selenium. Chicken drumstick is also a good source of choline, pantothenic acid, and vitamin B12.'");
        setupInsertToFood("4, 'Chicken Wing', 100, 'g', 1, 'wing', 203, 848, 30, 0, 8.1, 203, 30, 0, 8.1, 1, 0, 1, 'chicken_wing_a', 'chicken_wing_b', 'chicken_wing_c', 'Chicken wing is a great source of lean protein. It is also a great source of vitamin B6, phosphorus, niacin, and selenium. Chicken wing is also a good source of choline, pantothenic acid, and vitamin B12.'");
        setupInsertToFood("5, 'Chicken Leg', 100, 'g', 1, 'leg', 184, 768, 28, 0, 7.8, 184, 28, 0, 7.8, 1, 0, 1, 'chicken_leg_a', 'chicken_leg_b', 'chicken_leg_c', 'Chicken leg is a great source of lean protein. It is also a great source of vitamin B6, phosphorus, niacin, and selenium. Chicken leg is also a good source of choline, pantothenic acid, and vitamin B12.'");
        setupInsertToFood("6, 'Chicken Liver', 100, 'g', 1, 'liver', 116, 485, 17, 0, 3.6, 116, 17, 0, 3.6, 1, 0, 1, 'chicken_liver_a', 'chicken_liver_b', 'chicken_liver_c', 'Chicken liver is a great source of lean protein. It is also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Chicken liver is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("7, 'Chicken Heart', 100, 'g', 1, 'heart', 153, 639, 16, 0, 12, 153, 16, 0, 12, 1, 0, 1, 'chicken_heart_a', 'chicken_heart_b', 'chicken_heart_c', 'Chicken heart is a great source of lean protein. It is also a great source of vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Chicken heart is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("8, 'Eggs', 100, 'g', 1, 'egg', 155, 647, 13, 1.1, 11, 155, 13, 1.1, 11, 1, 0, 1, 'egg_a', 'egg_b', 'egg_c', 'Eggs are a great source of lean protein. They are also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Eggs are also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("9, 'Egg White', 100, 'g', 1, 'egg', 52, 218, 11, 0, 0.2, 52, 11, 0, 0.2, 1, 0, 1, 'egg_white_a', 'egg_white_b', 'egg_white_c', 'Egg white is a great source of lean protein. It is also a great source of vitamin B6, phosphorus, niacin, and selenium. Egg white is also a good source of choline, pantothenic acid, and vitamin B12.'");
        setupInsertToFood("10, 'Egg Yolk', 100, 'g', 1, 'egg', 322, 1345, 16, 1.1, 27, 322, 16, 1.1, 27, 1, 0, 1, 'egg_yolk_a', 'egg_yolk_b', 'egg_yolk_c', 'Egg yolk is a great source of lean protein. It is also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Egg yolk is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("11, 'Egg Boiled', 100, 'g', 1, 'egg', 155, 647, 13, 1.1, 11, 155, 13, 1.1, 11, 1, 0, 1, 'egg_boiled_a', 'egg_boiled_b', 'egg_boiled_c', 'Egg boiled is a great source of lean protein. It is also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Egg boiled is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("12, 'Egg Fried', 100, 'g', 1, 'egg', 196, 820, 14, 1.1, 15, 196, 14, 1.1, 15, 1, 0, 1, 'egg_fried_a', 'egg_fried_b', 'egg_fried_c', 'Egg fried is a great source of lean protein. It is also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Egg fried is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("13, 'Egg Scrambled', 100, 'g', 1, 'egg', 196, 820, 14, 1.1, 15, 196, 14, 1.1, 15, 1, 0, 1, 'egg_scrambled_a', 'egg_scrambled_b', 'egg_scrambled_c', 'Egg scrambled is a great source of lean protein. It is also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Egg scrambled is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("14, 'Egg Omelette', 100, 'g', 1, 'egg', 154, 644, 13, 1.1, 11, 154, 13, 1.1, 11, 1, 0, 1, 'egg_omelette_a', 'egg_omelette_b', 'egg_omelette_c', 'Egg omelette is a great source of lean protein. It is also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Egg omelette is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("15, 'Egg Poached', 100, 'g', 1, 'egg', 143, 598, 13, 1.1, 10, 143, 13, 1.1, 10, 1, 0, 1, 'egg_poached_a', 'egg_poached_b', 'egg_poached_c', 'Egg poached is a great source of lean protein. It is also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Egg poached is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("16, 'Egg Raw', 100, 'g', 1, 'egg', 143, 598, 13, 1.1, 10, 143, 13, 1.1, 10, 1, 0, 1, 'egg_raw_a', 'egg_raw_b', 'egg_raw_c', 'Egg raw is a great source of lean protein. It is also a great source of vitamin A, vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Egg raw is also a good source of riboflavin, niacin, and pantothenic acid.'");
        setupInsertToFood("17, 'Ribeye', 100, 'g', 1, 'steak', 291, 1217, 20, 0, 23, 291, 20, 0, 23, 1, 0, 1, 'ribeye_a', 'ribeye_b', 'ribeye_c', 'Ribeye is a great source of lean protein. It is also a great source of vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Ribeye is also a good source of niacin and pantothenic acid.'");
        setupInsertToFood("18, 'Sirloin', 100, 'g', 1, 'steak', 219, 916, 21, 0, 15, 219, 21, 0, 15, 1, 0, 1, 'sirloin_a', 'sirloin_b', 'sirloin_c', 'Sirloin is a great source of lean protein. It is also a great source of vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Sirloin is also a good source of niacin and pantothenic acid.'");
        setupInsertToFood("19, 'T-Bone', 100, 'g', 1, 'steak', 195, 817, 21, 0, 13, 195, 21, 0, 13, 1, 0, 1, 't_bone_a', 't_bone_b', 't_bone_c', 'T-Bone is a great source of lean protein. It is also a great source of vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. T-Bone is also a good source of niacin and pantothenic acid.'");
        setupInsertToFood("20, 'Porterhouse', 100, 'g', 1, 'steak', 195, 817, 21, 0, 13, 195, 21, 0, 13, 1, 0, 1, 'porterhouse_a', 'porterhouse_b', 'porterhouse_c', 'Porterhouse is a great source of lean protein. It is also a great source of vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Porterhouse is also a good source of niacin and pantothenic acid.'");
        setupInsertToFood("21, 'Tenderloin', 100, 'g', 1, 'steak', 143, 598, 13, 1.1, 10, 143, 13, 1.1, 10, 1, 0, 1, 'tenderloin_a', 'tenderloin_b', 'tenderloin_c', 'Tenderloin is a great source of lean protein. It is also a great source of vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Tenderloin is also a good source of niacin and pantothenic acid.'");
        setupInsertToFood("22, 'Ground Beef', 100, 'g', 1, 'steak', 217, 909, 21, 0, 15, 217, 21, 0, 15, 1, 0, 1, 'ground_beef_a', 'ground_beef_b', 'ground_beef_c', 'Ground beef is a great source of lean protein. It is also a great source of vitamin B6, vitamin B12, iron, phosphorus, zinc, copper, and selenium. Ground beef is also a good source of niacin and pantothenic acid.'");
        setupInsertToFood("23, 'Pasta', 100, 'g', 1, 'cup', 131, 548, 5, 32, 1, 131, 5, 0, 1, 1, 0, 1, 'pasta_a', 'pasta_b', 'pasta_c', 'Pasta is a great source of carbohydrates. It is also a great source of manganese. Pasta is also a good source of thiamin and folate.'");
        setupInsertToFood("24, 'Rice', 100, 'g', 1, 'cup', 130, 545, 2, 0, 0, 130, 2, 0, 0, 1, 0, 1, 'rice_a', 'rice_b', 'rice_c', 'Rice is a great source of carbohydrates. It is also a great source of manganese. Rice is also a good source of thiamin and folate.'");
        setupInsertToFood("25, 'Potato', 100, 'g', 1, 'potato', 77, 322, 2, 0, 0, 77, 2, 0, 0, 1, 0, 1, 'potato_a', 'potato_b', 'potato_c', 'Potato is a great source of carbohydrates. It is also a great source of vitamin C, vitamin B6, potassium, manganese, and fiber. Potato is also a good source of niacin, pantothenic acid, phosphorus, and copper.'");
        setupInsertToFood("26, 'Sweet Potato', 100, 'g', 1, 'potato', 86, 360, 2, 0, 0, 86, 2, 0, 0, 1, 0, 1, 'sweet_potato_a', 'sweet_potato_b', 'sweet_potato_c', 'Sweet potato is a great source of carbohydrates. It is also a great source of vitamin A, vitamin C, vitamin B6, potassium, manganese, and fiber. Sweet potato is also a good source of niacin, pantothenic acid, phosphorus, and copper.'");
        setupInsertToFood("27, 'Broccoli', 100, 'g', 1, 'cup', 34, 142, 3, 0, 0, 34, 3, 0, 0, 1, 0, 1, 'broccoli_a', 'broccoli_b', 'broccoli_c', 'Broccoli is a great source of vitamin C, vitamin K, vitamin A, folate, and fiber. Broccoli is also a good source of manganese, phosphorus, potassium, magnesium, and iron.'");
        setupInsertToFood("28, 'Carrot', 100, 'g', 1, 'carrot', 41, 173, 1, 0, 0, 41, 1, 0, 0, 1, 0, 1, 'carrot_a', 'carrot_b', 'carrot_c', 'Carrot is a great source of vitamin A, vitamin C, vitamin K, potassium, and fiber. Carrot is also a good source of manganese, niacin, vitamin B6, folate, and copper.'");
        setupInsertToFood("29, 'Cauliflower', 100, 'g', 1, 'cup', 25, 105, 2, 0, 0, 25, 2, 0, 0, 1, 0, 1, 'cauliflower_a', 'cauliflower_b', 'cauliflower_c', 'Cauliflower is a great source of vitamin C, vitamin K, folate, and fiber. Cauliflower is also a good source of vitamin B6, potassium, manganese, and magnesium.'");
        setupInsertToFood("30, 'Corn', 100, 'g', 1, 'cup', 86, 360, 3, 0, 0, 86, 3, 0, 0, 1, 0, 1, 'corn_a', 'corn_b', 'corn_c', 'Corn is a great source of vitamin C, thiamin, and folate. Corn is also a good source of vitamin B6, phosphorus, and manganese.'");
        setupInsertToFood("31, 'Cucumber', 100, 'g', 1, 'cup', 16, 67, 1, 0, 0, 16, 1, 0, 0, 1, 0, 1, 'cucumber_a', 'cucumber_b', 'cucumber_c', 'Cucumber is a great source of vitamin K and potassium. Cucumber is also a good source of vitamin C, magnesium, and manganese.'");
        setupInsertToFood("32, 'Lettuce', 100, 'g', 1, 'cup', 15, 63, 1, 0, 0, 15, 1, 0, 0, 1, 0, 1, 'lettuce_a', 'lettuce_b', 'lettuce_c', 'Lettuce is a great source of vitamin A, vitamin K, and folate. Lettuce is also a good source of vitamin C, manganese, and potassium.'");
        setupInsertToFood("33, 'Mushroom', 100, 'g', 1, 'cup', 22, 92, 3, 0, 0, 22, 3, 0, 0, 1, 0, 1, 'mushroom_a', 'mushroom_b', 'mushroom_c', 'Mushroom is a great source of vitamin D, vitamin B6, and potassium. Mushroom is also a good source of vitamin C, thiamin, folate, and magnesium.'");
        setupInsertToFood("34, 'Onion', 100, 'g', 1, 'cup', 40, 167, 1, 0, 0, 40, 1, 0, 0, 1, 0, 1, 'onion_a', 'onion_b', 'onion_c', 'Onion is a great source of vitamin C, vitamin B6, and potassium. Onion is also a good source of fiber, folate, and manganese.'");
        setupInsertToFood("35, 'Peas', 100, 'g', 1, 'cup', 81, 339, 4, 0, 0, 81, 4, 0, 0, 1, 0, 1, 'peas_a', 'peas_b', 'peas_c', 'Peas is a great source of vitamin K, manganese, and fiber. Peas is also a good source of vitamin C, thiamin, folate, and phosphorus.'");
        setupInsertToFood("36, 'Pepper', 100, 'g', 1, 'cup', 20, 84, 1, 0, 0, 20, 1, 0, 0, 1, 0, 1, 'pepper_a', 'pepper_b', 'pepper_c', 'Pepper is a great source of vitamin C, vitamin A, and potassium. Pepper is also a good source of fiber, vitamin B6, and folate.'");
        setupInsertToFood("37, 'Spinach', 100, 'g', 1, 'cup', 23, 97, 3, 0, 0, 23, 3, 0, 0, 1, 0, 1, 'spinach_a', 'spinach_b', 'spinach_c', 'Spinach is a great source of vitamin A, vitamin C, and vitamin K. Spinach is also a good source of manganese, folate, and magnesium.'");
        setupInsertToFood("38, 'Tomato', 100, 'g', 1, 'cup', 18, 74, 1, 0, 0, 18, 1, 0, 0, 1, 0, 1, 'tomato_a', 'tomato_b', 'tomato_c', 'Tomato is a great source of vitamin C, vitamin K, and potassium. Tomato is also a good source of vitamin A, manganese, and fiber.'");
        setupInsertToFood("39, 'Apple', 100, 'g', 1, 'apple', 52, 218, 0, 0, 0, 52, 0, 0, 0, 1, 0, 1, 'apple_a', 'apple_b', 'apple_c', 'Apple is a great source of fiber and vitamin C. Apple is also a good source of vitamin K, potassium, and manganese.'");
        setupInsertToFood("40, 'Banana', 100, 'g', 1, 'banana', 89, 371, 1, 0, 0, 89, 1, 0, 0, 1, 0, 1, 'banana_a', 'banana_b', 'banana_c', 'Banana is a great source of vitamin B6, manganese, and fiber. Banana is also a good source of vitamin C, potassium, and biotin.'");
        setupInsertToFood("41, 'Grapefruit', 100, 'g', 1, 'grapefruit', 32, 135, 0, 0, 0, 32, 0, 0, 0, 1, 0, 1, 'grapefruit_a', 'grapefruit_b', 'grapefruit_c', 'Grapefruit is a great source of vitamin C, vitamin A, and potassium. Grapefruit is also a good source of fiber, thiamin, and folate.'");
        setupInsertToFood("42, 'Grapes', 100, 'g', 1, 'cup', 69, 288, 1, 0, 0, 69, 1, 0, 0, 1, 0, 1, 'grapes_a', 'grapes_b', 'grapes_c', 'Grapes is a great source of vitamin K and copper. Grapes is also a good source of vitamin C, vitamin B6, and potassium.'");
        setupInsertToFood("43, 'Lemon', 100, 'g', 1, 'lemon', 29, 121, 0, 0, 0, 29, 0, 0, 0, 1, 0, 1, 'lemon_a', 'lemon_b', 'lemon_c', 'Lemon is a great source of vitamin C, vitamin B6, and potassium. Lemon is also a good source of thiamin, folate, and magnesium.'");
        setupInsertToFood("44, 'Lime', 100, 'g', 1, 'lime', 30, 126, 0, 0, 0, 30, 0, 0, 0, 1, 0, 1, 'lime_a', 'lime_b', 'lime_c', 'Lime is a great source of vitamin C, vitamin B6, and potassium. Lime is also a good source of thiamin, folate, and magnesium.'");
        setupInsertToFood("45, 'Orange', 100, 'g', 1, 'orange', 47, 196, 0, 0, 0, 47, 0, 0, 0, 1, 0, 1, 'orange_a', 'orange_b', 'orange_c', 'Orange is a great source of vitamin C, thiamin, and folate. Orange is also a good source of potassium and fiber.'");
        setupInsertToFood("46, 'Peach', 100, 'g', 1, 'peach', 39, 163, 0, 0, 0, 39, 0, 0, 0, 1, 0, 1, 'peach_a', 'peach_b', 'peach_c', 'Peach is a great source of vitamin C, vitamin A, and potassium. Peach is also a good source of fiber, vitamin K, and copper.'");
        setupInsertToFood("47, 'Pear', 100, 'g', 1, 'pear', 57, 239, 0, 0, 0, 57, 0, 0, 0, 1, 0, 1, 'pear_a', 'pear_b', 'pear_c', 'Pear is a great source of fiber, vitamin C, and vitamin K. Pear is also a good source of copper, vitamin B2, and potassium.'");
        setupInsertToFood("48, 'Pineapple', 100, 'g', 1, 'cup', 50, 209, 0, 0, 0, 50, 0, 0, 0, 1, 0, 1, 'pineapple_a', 'pineapple_b', 'pineapple_c', 'Pineapple is a great source of vitamin C, manganese, and fiber. Pineapple is also a good source of vitamin B1, vitamin B6, and copper.'");
        setupInsertToFood("49, 'Plum', 100, 'g', 1, 'plum', 46, 194, 0, 0, 0, 46, 0, 0, 0, 1, 0, 1, 'plum_a', 'plum_b', 'plum_c', 'Plum is a great source of vitamin C, vitamin K, and copper. Plum is also a good source of vitamin A, vitamin B2, and potassium.'");
        setupInsertToFood("50, 'Raisins', 100, 'g', 1, 'cup', 299, 1251, 0, 0, 0, 299, 0, 0, 0, 1, 0, 1, 'raisins_a', 'raisins_b', 'raisins_c', 'Raisins is a great source of potassium, fiber, and copper. Raisins is also a good source of vitamin B6, manganese, and magnesium.'");
        setupInsertToFood("51, 'Strawberry', 100, 'g', 1, 'cup', 33, 136, 0, 0, 0, 33, 0, 0, 0, 1, 0, 1, 'strawberry_a', 'strawberry_b', 'strawberry_c', 'Strawberry is a great source of vitamin C, manganese, and fiber. Strawberry is also a good source of iodine, folate, and copper.'");
        setupInsertToFood("52, 'Watermelon', 100, 'g', 1, 'cup', 30, 125, 0, 0, 0, 30, 0, 0, 0, 1, 0, 1, 'watermelon_a', 'watermelon_b', 'watermelon_c', 'Watermelon is a great source of vitamin C, vitamin A, and potassium. Watermelon is also a good source of magnesium, vitamin B1, and vitamin B6.'");
        setupInsertToFood("53, 'Asparagus', 100, 'g', 1, 'cup', 20, 85, 0, 0, 0, 20, 0, 0, 0, 1, 0, 1, 'asparagus_a', 'asparagus_b', 'asparagus_c', 'Asparagus is a great source of vitamin K, vitamin A, and folate. Asparagus is also a good source of vitamin C, vitamin E, and vitamin B1.'");
        setupInsertToFood("54, 'Broccoli', 100, 'g', 1, 'cup', 34, 142, 0, 0, 0, 34, 0, 0, 0, 1, 0, 1, 'broccoli_a', 'broccoli_b', 'broccoli_c', 'Broccoli is a great source of vitamin C, vitamin K, and folate. Broccoli is also a good source of vitamin A, manganese, and potassium.'");
        setupInsertToFood("55, 'Carrot', 100, 'g', 1, 'cup', 41, 173, 0, 0, 0, 41, 0, 0, 0, 1, 0, 1, 'carrot_a', 'carrot_b', 'carrot_c', 'Carrot is a great source of vitamin A, vitamin K, and potassium. Carrot is also a good source of vitamin C, vitamin B6, and manganese.'");
        setupInsertToFood("56, 'Celery', 100, 'g', 1, 'cup', 16, 67, 0, 0, 0, 16, 0, 0, 0, 1, 0, 1, 'celery_a', 'celery_b', 'celery_c', 'Celery is a great source of vitamin K, folate, and potassium. Celery is also a good source of vitamin A, vitamin C, and vitamin B2.'");
        setupInsertToFood("57, 'Corn', 100, 'g', 1, 'cup', 86, 360, 0, 0, 0, 86, 0, 0, 0, 1, 0, 1, 'corn_a', 'corn_b', 'corn_c', 'Corn is a great source of vitamin C, folate, and fiber. Corn is also a good source of vitamin B1, vitamin B5, and vitamin B3.'");
        setupInsertToFood("58, 'Cucumber', 100, 'g', 1, 'cup', 16, 67, 0, 0, 0, 16, 0, 0, 0, 1, 0, 1, 'cucumber_a', 'cucumber_b', 'cucumber_c', 'Cucumber is a great source of vitamin K, potassium, and copper. Cucumber is also a good source of vitamin C, magnesium, and vitamin B1.'");
        setupInsertToFood("59, 'Green Pepper', 100, 'g', 1, 'cup', 20, 84, 0, 0, 0, 20, 0, 0, 0, 1, 0, 1, 'green_pepper_a', 'green_pepper_b', 'green_pepper_c', 'Green Pepper is a great source of vitamin C, vitamin A, and vitamin B6. Green Pepper is also a good source of vitamin K, potassium, and manganese.'");
        setupInsertToFood("60, 'Bread', 100, 'g', 1, 'slice', 265, 1110, 0, 0, 0, 265, 0, 0, 0, 1, 0, 1, 'bread_a', 'bread_b', 'bread_c', 'Bread is a great source of manganese, selenium, and fiber. Bread is also a good source of vitamin B1, vitamin B2, and vitamin B3.'");
        setupInsertToFood("61, 'Couscous', 100, 'g', 1, 'cup', 112, 472, 0, 0, 0, 112, 0, 0, 0, 1, 0, 1, 'couscous_a', 'couscous_b', 'couscous_c', 'Couscous is a great source of selenium, manganese, and fiber. Couscous is also a good source of vitamin B1, vitamin B3, and vitamin B6.'");
        setupInsertToFood("62, 'Oatmeal', 100, 'g', 1, 'cup', 389, 1630, 0, 0, 0, 389, 0, 0, 0, 1, 0, 1, 'oatmeal_a', 'oatmeal_b', 'oatmeal_c', 'Oatmeal is a great source of manganese, selenium, and phosphorus. Oatmeal is also a good source of vitamin B1, magnesium, and fiber.'");
        setupInsertToFood("63, 'Lamb', 100, 'g', 1, 'cup', 294, 1230, 0, 0, 0, 294, 0, 0, 0, 1, 0, 1, 'lamb_a', 'lamb_b', 'lamb_c', 'Lamb is a great source of selenium, vitamin B12, and zinc. Lamb is also a good source of vitamin B3, phosphorus, and iron.'");
        setupInsertToFood("64, 'Pork', 100, 'g', 1, 'cup', 297, 1240, 0, 0, 0, 297, 0, 0, 0, 1, 0, 1, 'pork_a', 'pork_b', 'pork_c', 'Pork is a great source of vitamin B1, vitamin B6, and phosphorus. Pork is also a good source of vitamin B3, zinc, and selenium.'");
        setupInsertToFood("65, 'Turkey', 100, 'g', 1, 'cup', 189, 790, 0, 0, 0, 189, 0, 0, 0, 1, 0, 1, 'turkey_a', 'turkey_b', 'turkey_c', 'Turkey is a great source of vitamin B3, vitamin B6, and phosphorus. Turkey is also a good source of vitamin B1, zinc, and selenium.'");
        setupInsertToFood("66, 'Nuts', 100, 'g', 1, 'cup', 607, 2540, 0, 0, 0, 607, 0, 0, 0, 1, 0, 1, 'nuts_a', 'nuts_b', 'nuts_c', 'Nuts is a great source of manganese, copper, and magnesium. Nuts is also a good source of vitamin B1, vitamin B6, and phosphorus.'");
        setupInsertToFood("67, 'Peanut Butter', 100, 'g', 1, 'cup', 588, 2460, 0, 0, 0, 588, 0, 0, 0, 1, 0, 1, 'peanut_butter_a', 'peanut_butter_b', 'peanut_butter_c', 'Peanut Butter is a great source of manganese, vitamin B3, and vitamin E. Peanut Butter is also a good source of vitamin B1, vitamin B6, and phosphorus.'");
        setupInsertToFood("68, 'Tofu', 100, 'g', 1, 'cup', 76, 320, 0, 0, 0, 76, 0, 0, 0, 1, 0, 1, 'tofu_a', 'tofu_b', 'tofu_c', 'Tofu is a great source of selenium, manganese, and calcium. Tofu is also a good source of iron, phosphorus, and magnesium.'");
        setupInsertToFood("69, 'Yogurt', 100, 'g', 1, 'cup', 61, 256, 0, 0, 0, 61, 0, 0, 0, 1, 0, 1, 'yogurt_a', 'yogurt_b', 'yogurt_c', 'Yogurt is a great source of calcium, phosphorus, and vitamin B5. Yogurt is also a good source of protein, zinc, and potassium.'");
        setupInsertToFood("70, 'Milk', 100, 'g', 1, 'cup', 61, 256, 0, 0, 0, 61, 0, 0, 0, 1, 0, 1, 'milk_a', 'milk_b', 'milk_c', 'Milk is a great source of calcium, phosphorus, and vitamin B2. Milk is also a good source of vitamin B12, protein, and vitamin A.'");
        setupInsertToFood("71, 'Cheese', 100, 'g', 1, 'cup', 371, 1550, 0, 0, 0, 371, 0, 0, 0, 1, 0, 1, 'cheese_a', 'cheese_b', 'cheese_c', 'Cheese is a great source of calcium, phosphorus, and selenium. Cheese is also a good source of vitamin B2, vitamin B12, and protein.'");
        setupInsertToFood("72, 'Fish', 100, 'g', 1, 'cup', 206, 862, 0, 0, 0, 206, 0, 0, 0, 1, 0, 1, 'fish_a', 'fish_b', 'fish_c', 'Fish is a great source of vitamin B12, vitamin D, and selenium. Fish is also a good source of protein, phosphorus, and vitamin B6.'");
        setupInsertToFood("73, 'Salmon', 100, 'g', 1, 'cup', 208, 870, 0, 0, 0, 208, 0, 0, 0, 1, 0, 1, 'salmon_a', 'salmon_b', 'salmon_c', 'Salmon is a great source of vitamin B12, vitamin D, and selenium. Salmon is also a good source of protein, phosphorus, and vitamin B6.'");
        setupInsertToFood("74, 'Avocado', 100, 'g', 1, 'cup', 160, 670, 0, 0, 0, 160, 0, 0, 0, 1, 0, 1, 'avocado_a', 'avocado_b', 'avocado_c', 'Avocado is a great source of vitamin K, folate, and vitamin C. Avocado is also a good source of potassium, vitamin B5, and vitamin B6.'");
        setupInsertToFood("75, 'Aubergine', 100, 'g', 1, 'cup', 25, 104, 0, 0, 0, 25, 0, 0, 0, 1, 0, 1, 'aubergine_a', 'aubergine_b', 'aubergine_c', 'Aubergine is a great source of dietary fiber, vitamin B1, and copper. Aubergine is also a good source of manganese, vitamin B6, and folate.'");
    }


    //insert example user into database
    public void insertAllUsers(){
        DBAdapter db = new DBAdapter(context);
        db.open();

        //TODO
        //db.insert("")
        db.close();
    }

}
